"""create simulation sessions and checkpoints

Revision ID: dd52daa2a6f6
Revises:
Create Date: 2026-08-09 19:20:45.970270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd52daa2a6f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column("trajectory_plan_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INITIALIZED", "RUNNING", "PAUSED", "COMPLETED", "FAILED", name="simulation_status"
            ),
            nullable=False,
        ),
        sa.Column("simulation_speed", sa.Integer(), nullable=False),
        sa.Column("integration_step_s", sa.Float(), nullable=False),
        sa.Column(
            "initial_state_vector",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("engine_thrust_n", sa.Float(), nullable=False),
        sa.Column("engine_specific_impulse_s", sa.Float(), nullable=False),
        sa.Column("oxygen_kg", sa.Float(), nullable=False),
        sa.Column("oxygen_consumption_rate_kg_s", sa.Float(), nullable=False),
        sa.Column("battery_kwh", sa.Float(), nullable=False),
        sa.Column("power_consumption_kw", sa.Float(), nullable=False),
        sa.Column("checkpoint_interval_s", sa.Float(), nullable=False),
        sa.Column(
            "planned_maneuvers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_sessions_mission_id"),
        "simulation_sessions",
        ["mission_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_simulation_sessions_status"), "simulation_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_simulation_sessions_trajectory_plan_id"),
        "simulation_sessions",
        ["trajectory_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_sessions_vehicle_id"),
        "simulation_sessions",
        ["vehicle_id"],
        unique=False,
    )
    op.create_table(
        "simulation_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("simulation_session_id", sa.Uuid(), nullable=False),
        sa.Column("simulated_time_s", sa.Float(), nullable=False),
        sa.Column(
            "state_vector",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "maneuver_states",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("oxygen_kg", sa.Float(), nullable=False),
        sa.Column("battery_kwh", sa.Float(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "INITIALIZED",
                "PERIODIC",
                "PAUSED",
                "MANEUVER_COMPLETED",
                "COMPLETED",
                name="checkpoint_reason",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_session_id"], ["simulation_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_checkpoints_simulation_session_id"),
        "simulation_checkpoints",
        ["simulation_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_simulation_checkpoints_simulation_session_id"), table_name="simulation_checkpoints"
    )
    op.drop_table("simulation_checkpoints")
    op.drop_index(op.f("ix_simulation_sessions_vehicle_id"), table_name="simulation_sessions")
    op.drop_index(
        op.f("ix_simulation_sessions_trajectory_plan_id"), table_name="simulation_sessions"
    )
    op.drop_index(op.f("ix_simulation_sessions_status"), table_name="simulation_sessions")
    op.drop_index(op.f("ix_simulation_sessions_mission_id"), table_name="simulation_sessions")
    op.drop_table("simulation_sessions")
    # ### end Alembic commands ###
