from enum import StrEnum


class MissionType(StrEnum):
    LEO = "LEO"
    LEO_RENDEZVOUS = "LEO_RENDEZVOUS"
    LUNAR = "LUNAR"


class SpacecraftStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    MAINTENANCE = "MAINTENANCE"
    UNAVAILABLE = "UNAVAILABLE"


class VehicleType(StrEnum):
    CREW_CAPSULE = "CREW_CAPSULE"
    ORBITAL_VEHICLE = "ORBITAL_VEHICLE"
    LUNAR_CAPABLE = "LUNAR_CAPABLE"


class ValidationViolationCode(StrEnum):
    VEHICLE_NOT_AVAILABLE = "VEHICLE_NOT_AVAILABLE"
    MISSION_TYPE_NOT_SUPPORTED = "MISSION_TYPE_NOT_SUPPORTED"
    CREW_CAPACITY_EXCEEDED = "CREW_CAPACITY_EXCEEDED"
    PAYLOAD_CAPACITY_EXCEEDED = "PAYLOAD_CAPACITY_EXCEEDED"
    MISSION_DURATION_EXCEEDED = "MISSION_DURATION_EXCEEDED"
