from enum import StrEnum


class CommandStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    LOST = "LOST"


class CommandType(StrEnum):
    START_MANEUVER = "START_MANEUVER"
    CANCEL_MANEUVER = "CANCEL_MANEUVER"
    RECALCULATE_TRAJECTORY = "RECALCULATE_TRAJECTORY"
    CHANGE_ORBIT = "CHANGE_ORBIT"
    PAUSE_SIMULATION = "PAUSE_SIMULATION"
    RESUME_SIMULATION = "RESUME_SIMULATION"
    RETURN_TO_EARTH = "RETURN_TO_EARTH"
    EMERGENCY_ABORT = "EMERGENCY_ABORT"


class SignalStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    LOST = "LOST"
