"""add prepare mission saga steps

Revision ID: 28daecc0a05d
Revises:
Create Date: 2026-08-11 15:36:55.797133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28daecc0a05d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "mission_type",
            sa.Enum("LEO", "LEO_RENDEZVOUS", "LUNAR", name="mission_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PLANNING",
                "PREPARING",
                "READY",
                "IN_PROGRESS",
                "COMPLETED",
                "ABORTING",
                "ABORTED",
                "FAILED_PREPARATION",
                "FAILED",
                name="mission_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "mission_phase",
            sa.Enum(
                "ORBIT_INSERTION",
                "ORBIT_COAST",
                "ORBIT_MAINTENANCE",
                "RENDEZVOUS_APPROACH",
                "TRANSLUNAR_COAST",
                "LUNAR_ORBIT_INSERTION",
                "DESCENT",
                "RETURN_TRANSFER",
                "DEORBIT",
                name="mission_phase",
            ),
            nullable=True,
        ),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("crew_count", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column(
            "target_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("planned_launch_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("simulation_speed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_missions_status"), "missions", ["status"], unique=False)
    op.create_index(op.f("ix_missions_vehicle_id"), "missions", ["vehicle_id"], unique=False)
    op.create_table(
        "mission_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "MISSION_CREATED",
                "PREPARATION_REQUESTED",
                "STATUS_CHANGED",
                "PHASE_CHANGED",
                "MISSION_STARTED",
                "ABORT_REQUESTED",
                "MISSION_COMPLETED",
                "MISSION_FAILED",
                name="mission_event_type",
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_events_event_type"), "mission_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_mission_events_mission_id"), "mission_events", ["mission_id"], unique=False
    )
    op.create_index(
        op.f("ix_mission_events_occurred_at"), "mission_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "saga_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("saga_id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "VEHICLE_RESERVATION",
                "TRAJECTORY_PLANNING",
                "RESOURCE_VALIDATION",
                "COMMUNICATION_PROFILE",
                "SIMULATION_INITIALIZATION",
                name="saga_step_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "COMPENSATING",
                "COMPENSATED",
                name="saga_step_status",
            ),
            nullable=False,
        ),
        sa.Column("request_event_id", sa.Uuid(), nullable=True),
        sa.Column("result_event_id", sa.Uuid(), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("compensated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("saga_id", "step_type", name="uq_saga_steps_saga_step"),
    )
    op.create_index(op.f("ix_saga_steps_mission_id"), "saga_steps", ["mission_id"], unique=False)
    op.create_index(op.f("ix_saga_steps_saga_id"), "saga_steps", ["saga_id"], unique=False)
    op.create_index(op.f("ix_saga_steps_status"), "saga_steps", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saga_steps_status"), table_name="saga_steps")
    op.drop_index(op.f("ix_saga_steps_saga_id"), table_name="saga_steps")
    op.drop_index(op.f("ix_saga_steps_mission_id"), table_name="saga_steps")
    op.drop_table("saga_steps")
    op.drop_index(op.f("ix_mission_events_occurred_at"), table_name="mission_events")
    op.drop_index(op.f("ix_mission_events_mission_id"), table_name="mission_events")
    op.drop_index(op.f("ix_mission_events_event_type"), table_name="mission_events")
    op.drop_table("mission_events")
    op.drop_index(op.f("ix_missions_vehicle_id"), table_name="missions")
    op.drop_index(op.f("ix_missions_status"), table_name="missions")
    op.drop_table("missions")
    # ### end Alembic commands ###
