"""persist prepare saga payloads

Revision ID: 5f4d44e1d402
Revises: 28daecc0a05d
Create Date: 2026-08-11 17:25:59.578580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f4d44e1d402"
down_revision: str | Sequence[str] | None = "28daecc0a05d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saga_steps",
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "saga_steps",
        sa.Column(
            "result_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("saga_steps", "result_payload")
    op.drop_column("saga_steps", "request_payload")
    # ### end Alembic commands ###
