from enum import StrEnum


class MissionType(StrEnum):
    LEO = "LEO"
    LEO_RENDEZVOUS = "LEO_RENDEZVOUS"
    LUNAR = "LUNAR"


class MissionStatus(StrEnum):
    DRAFT = "DRAFT"
    PLANNING = "PLANNING"
    PREPARING = "PREPARING"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABORTING = "ABORTING"
    ABORTED = "ABORTED"
    FAILED_PREPARATION = "FAILED_PREPARATION"
    FAILED = "FAILED"


class MissionPhase(StrEnum):
    ORBIT_INSERTION = "ORBIT_INSERTION"
    ORBIT_COAST = "ORBIT_COAST"
    ORBIT_MAINTENANCE = "ORBIT_MAINTENANCE"
    RENDEZVOUS_APPROACH = "RENDEZVOUS_APPROACH"
    TRANSLUNAR_COAST = "TRANSLUNAR_COAST"
    LUNAR_ORBIT_INSERTION = "LUNAR_ORBIT_INSERTION"
    DESCENT = "DESCENT"
    RETURN_TRANSFER = "RETURN_TRANSFER"
    DEORBIT = "DEORBIT"


class MissionEventType(StrEnum):
    MISSION_CREATED = "MISSION_CREATED"
    PREPARATION_REQUESTED = "PREPARATION_REQUESTED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PHASE_CHANGED = "PHASE_CHANGED"
    MISSION_STARTED = "MISSION_STARTED"
    ABORT_REQUESTED = "ABORT_REQUESTED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_FAILED = "MISSION_FAILED"


class SagaStepType(StrEnum):
    VEHICLE_RESERVATION = "VEHICLE_RESERVATION"
    TRAJECTORY_PLANNING = "TRAJECTORY_PLANNING"
    RESOURCE_VALIDATION = "RESOURCE_VALIDATION"
    COMMUNICATION_PROFILE = "COMMUNICATION_PROFILE"
    SIMULATION_INITIALIZATION = "SIMULATION_INITIALIZATION"


class SagaStepStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"
