"""add mission resource reservations

Revision ID: 2d4a0da0a2ed
Revises: fa9a85027016
Create Date: 2026-08-13 13:44:43.923111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d4a0da0a2ed"
down_revision: str | Sequence[str] | None = "fa9a85027016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column("spacecraft_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["spacecraft_id"],
            ["spacecraft.id"],
            name=op.f("fk_resource_reservations_spacecraft_id_spacecraft"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_reservations")),
    )
    op.create_index(
        op.f("ix_resource_reservations_mission_id"),
        "resource_reservations",
        ["mission_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_resource_reservations_spacecraft_id"),
        "resource_reservations",
        ["spacecraft_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_resource_reservations_spacecraft_id"), table_name="resource_reservations"
    )
    op.drop_index(op.f("ix_resource_reservations_mission_id"), table_name="resource_reservations")
    op.drop_table("resource_reservations")
    # ### end Alembic commands ###
