"""add processed saga events

Revision ID: 7226379d4114
Revises: 2d4a0da0a2ed
Create Date: 2026-08-13 20:07:59.736252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7226379d4114"
down_revision: str | Sequence[str] | None = "2d4a0da0a2ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_processed_events")),
    )
    op.create_index(
        op.f("ix_processed_events_event_type"), "processed_events", ["event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_events_event_type"), table_name="processed_events")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
