"""create spacecraft table

Revision ID: fa9a85027016
Revises:
Create Date: 2026-08-06 22:36:56.065473

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa9a85027016"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spacecraft",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum(
                "CREW_CAPSULE",
                "ORBITAL_VEHICLE",
                "LUNAR_CAPABLE",
                name="vehicle_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "supported_mission_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("dry_mass_kg", sa.Float(), nullable=False),
        sa.Column("max_payload_kg", sa.Float(), nullable=False),
        sa.Column("crew_capacity", sa.Integer(), nullable=False),
        sa.Column("engine_thrust_n", sa.Float(), nullable=False),
        sa.Column("engine_specific_impulse_s", sa.Float(), nullable=False),
        sa.Column("propellant_capacity_kg", sa.Float(), nullable=False),
        sa.Column("oxygen_capacity_kg", sa.Float(), nullable=False),
        sa.Column("battery_capacity_kwh", sa.Float(), nullable=False),
        sa.Column("max_mission_duration_h", sa.Float(), nullable=False),
        sa.Column("max_acceleration_g", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "RESERVED",
                "MAINTENANCE",
                "UNAVAILABLE",
                name="spacecraft_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "battery_capacity_kwh > 0", name=op.f("ck_spacecraft_battery_capacity_positive")
        ),
        sa.CheckConstraint(
            "crew_capacity >= 0", name=op.f("ck_spacecraft_crew_capacity_non_negative")
        ),
        sa.CheckConstraint("dry_mass_kg > 0", name=op.f("ck_spacecraft_dry_mass_positive")),
        sa.CheckConstraint(
            "engine_specific_impulse_s > 0", name=op.f("ck_spacecraft_specific_impulse_positive")
        ),
        sa.CheckConstraint(
            "engine_thrust_n > 0", name=op.f("ck_spacecraft_engine_thrust_positive")
        ),
        sa.CheckConstraint(
            "max_acceleration_g > 0", name=op.f("ck_spacecraft_max_acceleration_positive")
        ),
        sa.CheckConstraint(
            "max_mission_duration_h > 0", name=op.f("ck_spacecraft_mission_duration_positive")
        ),
        sa.CheckConstraint(
            "max_payload_kg >= 0", name=op.f("ck_spacecraft_max_payload_non_negative")
        ),
        sa.CheckConstraint(
            "oxygen_capacity_kg >= 0", name=op.f("ck_spacecraft_oxygen_capacity_non_negative")
        ),
        sa.CheckConstraint(
            "propellant_capacity_kg > 0", name=op.f("ck_spacecraft_propellant_capacity_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spacecraft")),
    )
    op.create_index(op.f("ix_spacecraft_name"), "spacecraft", ["name"], unique=True)
    op.create_index(op.f("ix_spacecraft_status"), "spacecraft", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spacecraft_status"), table_name="spacecraft")
    op.drop_index(op.f("ix_spacecraft_name"), table_name="spacecraft")
    op.drop_table("spacecraft")
    # ### end Alembic commands ###
