"""create communication tables

Revision ID: a5e4845e0203
Revises:
Create Date: 2026-08-10 22:53:29.679097

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5e4845e0203"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "command_type",
            sa.Enum(
                "START_MANEUVER",
                "CANCEL_MANEUVER",
                "RECALCULATE_TRAJECTORY",
                "CHANGE_ORBIT",
                "PAUSE_SIMULATION",
                "RESUME_SIMULATION",
                "RETURN_TO_EARTH",
                "EMERGENCY_ABORT",
                name="command_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "QUEUED",
                "IN_TRANSIT",
                "DELIVERED",
                "EXECUTED",
                "REJECTED",
                "EXPIRED",
                "LOST",
                name="command_status",
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commands_command_type"), "commands", ["command_type"], unique=False)
    op.create_index(op.f("ix_commands_mission_id"), "commands", ["mission_id"], unique=False)
    op.create_index(op.f("ix_commands_status"), "commands", ["status"], unique=False)
    op.create_table(
        "communication_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("additional_latency_ms", sa.Float(), nullable=False),
        sa.Column("packet_loss_percent", sa.Float(), nullable=False),
        sa.Column(
            "signal_status",
            sa.Enum("AVAILABLE", "DEGRADED", "LOST", name="communication_signal_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_communication_profiles_mission_id"),
        "communication_profiles",
        ["mission_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_communication_profiles_signal_status"),
        "communication_profiles",
        ["signal_status"],
        unique=False,
    )
    op.create_table(
        "command_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "CREATED",
                "QUEUED",
                "IN_TRANSIT",
                "DELIVERED",
                "EXECUTED",
                "REJECTED",
                "EXPIRED",
                "LOST",
                name="command_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "CREATED",
                "QUEUED",
                "IN_TRANSIT",
                "DELIVERED",
                "EXECUTED",
                "REJECTED",
                "EXPIRED",
                "LOST",
                name="command_status",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["command_id"], ["commands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_logs_command_id"), "command_logs", ["command_id"], unique=False
    )
    op.create_index(
        op.f("ix_command_logs_occurred_at"), "command_logs", ["occurred_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_command_logs_occurred_at"), table_name="command_logs")
    op.drop_index(op.f("ix_command_logs_command_id"), table_name="command_logs")
    op.drop_table("command_logs")
    op.drop_index(
        op.f("ix_communication_profiles_signal_status"), table_name="communication_profiles"
    )
    op.drop_index(op.f("ix_communication_profiles_mission_id"), table_name="communication_profiles")
    op.drop_table("communication_profiles")
    op.drop_index(op.f("ix_commands_status"), table_name="commands")
    op.drop_index(op.f("ix_commands_mission_id"), table_name="commands")
    op.drop_index(op.f("ix_commands_command_type"), table_name="commands")
    op.drop_table("commands")
    # ### end Alembic commands ###
