from enum import StrEnum


class AlertSeverity(StrEnum):
    INFO = "INFO"
    CAUTION = "CAUTION"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertType(StrEnum):
    LOW_PROPELLANT = "LOW_PROPELLANT"
    PROPELLANT_RESERVE_VIOLATION = "PROPELLANT_RESERVE_VIOLATION"

    OXYGEN_LOW = "OXYGEN_LOW"
    OXYGEN_CRITICAL = "OXYGEN_CRITICAL"

    POWER_LOW = "POWER_LOW"

    TRAJECTORY_DEVIATION = "TRAJECTORY_DEVIATION"

    COMMUNICATION_DEGRADED = "COMMUNICATION_DEGRADED"
    COMMUNICATION_LOST = "COMMUNICATION_LOST"


class RecommendationType(StrEnum):
    CORRECTIVE_MANEUVER = "CORRECTIVE_MANEUVER"
    RETURN_TO_EARTH = "RETURN_TO_EARTH"
    ABORT = "ABORT"
